# SwiftLint Configuration for Melodic Drum Trainer

# Paths to include/exclude
included:
  - .
excluded:
  - .build
  - .swiftpm
  - DerivedData
  - Tests # Exclude test files from some rules

# Disabled rules
disabled_rules:
  - trailing_whitespace # Handled by Xcode
  - todo # Allow TODO comments during development

# Opt-in rules
opt_in_rules:
  - empty_count
  - empty_string
  - first_where
  - force_unwrapping
  - implicit_return
  - joined_default_parameter
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 2
    error: 3
  statement_level:
    warning: 5
    error: 10

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 100
  excluded:
    - id
    - x
    - y
    - z

# Custom rules
custom_rules:
  # Ensure proper property-based test naming
  property_test_naming:
    name: "Property Test Naming"
    regex: 'func test.*Property.*\(\)'
    message: "Property-based tests should include 'Property' in the function name"
    severity: warning
    
  # Ensure MIDI constants are properly defined
  midi_constants:
    name: "MIDI Constants"
    regex: '= [0-9]+\s*//.*MIDI'
    message: "MIDI constants should be properly documented"
    severity: warning

# Reporter type
reporter: "xcode"