// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "FingerDrumHero",
platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "FingerDrumHero",
            targets: ["AppModule"],
            bundleIdentifier: "com.example.fingerdrumhero",
            displayVersion: "1.0.1",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .asset("AccentColor"),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/AudioKit/AudioKit", exact: "5.3.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "AudioKit", package: "AudioKit")
            ],
            path: ".",
            exclude: ["Tests", "Documentation", ".github", ".swiftlint.yml", "CHANGELOG.md", "RESOURCE_FIX_SUMMARY.md", "CloudKitSyncDocumentation.md", "ExportOptions.plist", "CleanProject.swift", "ComprehensiveFix.swift", "FixDuplicateAssets.swift", "QuickDiagnostics.swift", "ResourceDiagnostics.swift", "ResourceTest.swift", "DrumTrainerModel.xcdatamodeld"],
            resources: [
                .process("Resources")
            ],
            swiftSettings: [
                .define("SWIFT_PACKAGE")
            ]
        )
    ]
)